### ISSUE TITLE
编译出来的jar包，没有主清单属性

### ISSUE THREAD

**Issue by rootphantomer** [potats0/cve_2020_14644#1]
编译好，-jar 提示没有主清单属性，-cp xxx.jar App提示找不到或无法加载主类 App。有点迷。 @potats0

**Comment by potats0** [comment]
java -jar运行

**Comment by rootphantomer** [comment]
@potats0 是java -jar 运行，提示没有没有主清单属性，我之前编译jar包是pom里指定了mainClass，我看你这个貌似没指定。我自行指定了一下，编译出来的也无法-jar包运行

**Comment by foolboy365** [comment]
公众号下载的也用不了。UnicodeSec未找到

**Comment by rootphantomer** [comment]
@foolboy365 编译好的那个，是作者之前的代码有一处if判断有小问题，导致进不去if内容，你把if条件删了，在源码层run一下，然后在用jar包就可以。现在作者的代码已经更新修复了那个bug。你可以用最新源码运行。

**Comment by foolboy365** [comment]
> @foolboy365 编译好的那个，是作者之前的代码有一处if判断有小问题，导致进不去if内容，你把if条件删了，在源码层run一下，然后在用jar包就可以。现在作者的代码已经更新修复了那个bug。你可以用最新源码运行。

我直接用你最新源码重新打包了，运行提示“错误: 找不到或无法加载主类 org.unicodesec.App”
